--------------------------------------------------------
-- Archivo creado  - martes-agosto-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TECNICO
--------------------------------------------------------

  CREATE TABLE "DERIK"."TECNICO" 
   (	"ID_TECNICO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"ESPECIALIDAD" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DERIK.TECNICO
SET DEFINE OFF;
Insert into DERIK.TECNICO (ID_TECNICO,NOMBRE,APELLIDO,ESPECIALIDAD,EMAIL,TELEFONO) values (1,'Jorge','Castro','Hardware','jorge.castro@novatech.com',70001111);
Insert into DERIK.TECNICO (ID_TECNICO,NOMBRE,APELLIDO,ESPECIALIDAD,EMAIL,TELEFONO) values (2,'Laura','Vega','Redes','laura.vega@novatech.com',70002222);
Insert into DERIK.TECNICO (ID_TECNICO,NOMBRE,APELLIDO,ESPECIALIDAD,EMAIL,TELEFONO) values (3,'Pedro','Mora','Software','pedro.mora@novatech.com',70003333);
--------------------------------------------------------
--  DDL for Index SYS_C008385
--------------------------------------------------------

  CREATE UNIQUE INDEX "DERIK"."SYS_C008385" ON "DERIK"."TECNICO" ("ID_TECNICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_AUDITAR_TECNICO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DERIK"."TRG_AUDITAR_TECNICO" 
AFTER DELETE ON tecnico
FOR EACH ROW
BEGIN
  INSERT INTO log_tecnico (id_tecnico, nombre_tecnico, fecha_eliminacion)
  VALUES (:OLD.id_tecnico, :OLD.nombre, SYSDATE);
END;

/
ALTER TRIGGER "DERIK"."TRG_AUDITAR_TECNICO" ENABLE;
--------------------------------------------------------
--  Constraints for Table TECNICO
--------------------------------------------------------

  ALTER TABLE "DERIK"."TECNICO" ADD PRIMARY KEY ("ID_TECNICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DERIK"."TECNICO" MODIFY ("ID_TECNICO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."TECNICO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."TECNICO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."TECNICO" MODIFY ("ESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."TECNICO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."TECNICO" MODIFY ("TELEFONO" NOT NULL ENABLE);
