--------------------------------------------------------
-- Archivo creado  - martes-agosto-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTADO_ORDEN
--------------------------------------------------------

  CREATE TABLE "DERIK"."ESTADO_ORDEN" 
   (	"ID_ESTADO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into DERIK.ESTADO_ORDEN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008392
--------------------------------------------------------

  CREATE UNIQUE INDEX "DERIK"."SYS_C008392" ON "DERIK"."ESTADO_ORDEN" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ESTADO_ORDEN
--------------------------------------------------------

  ALTER TABLE "DERIK"."ESTADO_ORDEN" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."ESTADO_ORDEN" ADD PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DERIK"."ESTADO_ORDEN" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
