--------------------------------------------------------
-- Archivo creado  - martes-agosto-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTRATO_MANTENIMIENTO
--------------------------------------------------------

  CREATE TABLE "DERIK"."CONTRATO_MANTENIMIENTO" 
   (	"ID_CONTRATO" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"TIPO_CONTRATO" VARCHAR2(50 BYTE), 
	"ESTADO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DERIK.CONTRATO_MANTENIMIENTO
SET DEFINE OFF;
Insert into DERIK.CONTRATO_MANTENIMIENTO (ID_CONTRATO,ID_CLIENTE,FECHA_INICIO,FECHA_FIN,TIPO_CONTRATO,ESTADO) values (1,1,to_date('01/01/25','DD/MM/RR'),to_date('31/12/25','DD/MM/RR'),'Anual','Activo');
Insert into DERIK.CONTRATO_MANTENIMIENTO (ID_CONTRATO,ID_CLIENTE,FECHA_INICIO,FECHA_FIN,TIPO_CONTRATO,ESTADO) values (2,2,to_date('15/02/25','DD/MM/RR'),to_date('15/08/25','DD/MM/RR'),'Semestral','Finalizado');
Insert into DERIK.CONTRATO_MANTENIMIENTO (ID_CONTRATO,ID_CLIENTE,FECHA_INICIO,FECHA_FIN,TIPO_CONTRATO,ESTADO) values (3,2,to_date('23/12/24','DD/MM/RR'),to_date('24/11/25','DD/MM/RR'),'Anual','Finalizado');
--------------------------------------------------------
--  DDL for Index SYS_C008406
--------------------------------------------------------

  CREATE UNIQUE INDEX "DERIK"."SYS_C008406" ON "DERIK"."CONTRATO_MANTENIMIENTO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONTRATO_MANTENIMIENTO
--------------------------------------------------------

  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" ADD PRIMARY KEY ("ID_CONTRATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" MODIFY ("TIPO_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CONTRATO_MANTENIMIENTO" MODIFY ("ESTADO" NOT NULL ENABLE);
