--------------------------------------------------------
-- Archivo creado  - martes-agosto-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "DERIK"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"TIPO_CLIENTE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEFONO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DERIK.CLIENTE
SET DEFINE OFF;
Insert into DERIK.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TIPO_CLIENTE,EMAIL,TELEFONO) values (43,'Derik','Monge','PERSONA','derik@gmail.com',84567890);
Insert into DERIK.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TIPO_CLIENTE,EMAIL,TELEFONO) values (1,'Andres','Ulloa','PERSONA','andres@gmail.com',88881234);
Insert into DERIK.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TIPO_CLIENTE,EMAIL,TELEFONO) values (2,'Maria','Fernandez','EMPRESA','maria@empresa.com',88992233);
Insert into DERIK.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TIPO_CLIENTE,EMAIL,TELEFONO) values (49,'der','monge','PERSONA','eme@gnma.com',23435656);
Insert into DERIK.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TIPO_CLIENTE,EMAIL,TELEFONO) values (50,'Derik','Monge','PERSONA','DERICK@GMAIL.COM',23344556);
--------------------------------------------------------
--  DDL for Index SYS_C008457
--------------------------------------------------------

  CREATE UNIQUE INDEX "DERIK"."SYS_C008457" ON "DERIK"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008458
--------------------------------------------------------

  CREATE UNIQUE INDEX "DERIK"."SYS_C008458" ON "DERIK"."CLIENTE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "DERIK"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CLIENTE" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DERIK"."CLIENTE" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
