--------------------------------------------------------
-- Archivo creado  - martes-agosto-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETALLE_SERVICIO
--------------------------------------------------------

  CREATE TABLE "DERIK"."DETALLE_SERVICIO" 
   (	"ID_DETALLE" NUMBER(*,0), 
	"ID_ORDEN" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"HORAS_TRABAJADAS" NUMBER(*,0), 
	"COSTO_APROXIMADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DERIK.DETALLE_SERVICIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008389
--------------------------------------------------------

  CREATE UNIQUE INDEX "DERIK"."SYS_C008389" ON "DERIK"."DETALLE_SERVICIO" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DETALLE_SERVICIO
--------------------------------------------------------

  ALTER TABLE "DERIK"."DETALLE_SERVICIO" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DERIK"."DETALLE_SERVICIO" MODIFY ("ID_DETALLE" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."DETALLE_SERVICIO" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."DETALLE_SERVICIO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."DETALLE_SERVICIO" MODIFY ("HORAS_TRABAJADAS" NOT NULL ENABLE);
  ALTER TABLE "DERIK"."DETALLE_SERVICIO" MODIFY ("COSTO_APROXIMADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_SERVICIO
--------------------------------------------------------

  ALTER TABLE "DERIK"."DETALLE_SERVICIO" ADD CONSTRAINT "FK_DETALLE_ORDEN" FOREIGN KEY ("ID_ORDEN")
	  REFERENCES "DERIK"."ORDEN_SERVICIO" ("ID_ORDEN") ENABLE;
